### ISSUE TITLE
Matrix example fails to compile with "Math.h: No such file or directory"

### ISSUE THREAD

**Issue by LenzGr** [scottyallen/SparkleShield#1]
I purchased the SparkleShield at 32C3 in Hamburg and the assembly worked out of the box, thanks to the great instructions.

I installed the SparkleShield library as described on http://sparkleshield.com/pages/instructions and started toying around with the examples included.

My controller is a [Seeduino Mega](http://www.seeedstudio.com/wiki/index.php?title=Seeeduino_Mega) based on the ATmega 1280 processor.

My development environment: Arduino: 1.6.7 (Linux), Board: "Arduino/Genuino Mega or Mega 2560, ATmega1280"

However, compiling the "Matrix" Demo initially failed with the following error:

```
/home/lenz/Arduino/libraries/SparkleShield/examples/Matrix/Matrix.ino:3:18: fatal error: Math.h: No such file or directory
 #include <Math.h>
                  ^
compilation terminated.
exit status 1
Error compiling.
```

Simply removing or commenting out the `#include <Math.h>` directive fixes the compile error and the demo works as expected.

**Comment by gedsic** [comment]
You have to include math.h, in lower case. I submitted a pull request.

**Comment by LenzGr** [comment]
@gedsic : I did not have to include `math.h` at all to get it compile and run. Simply commenting out the include directive fixed the build error and the resulting binary works without problems.

**Comment by gedsic** [comment]
@LenzGr You're right, math.h is included by default.

**Comment by scottyallen** [comment]
I merged the pull request, so closing this out.  I'll leave math.h in for clarity sake.
